on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    # ogni giorno alle 02:00 (ora UTC, quindi 04:00 italiane)
    - cron: '0 2 * * *'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ubuntu dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libcurl4-openssl-dev libfontconfig1-dev \
                              libharfbuzz-dev libfribidi-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Aggiorna i dati e i report provinciali
        run: |
          Rscript -e 'source("R/render_reports.R")'
          
      - name: Clean temporary files
        run: |
          rm -rf .Rhistory .RData .Rproj.user || true

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}